### PR TITLE
Skip extensions or files

### PR DESCRIPTION
**Pull request by cpanato**
This PR adds the feature to skip extensions or files to be checked or add the license header.
In some cases, we don't want to add the headers for some files, and will be useful if we can just skip those.

After I did the implementation I saw the PR: https://github.com/google/addlicense/pull/73

If the maintainers prefer the other approach I'm fine and we can close this PR

### CODE REVIEW

**Comment by lukehinds** [comment]
not a addlicense maintainer , but fwiy this is really useful. right now builds are failing as the code is looking for license headers in everything (including docs, , readmes, config files etc).

**Comment by mco-gh** [comment]
Hi, sorry for the delay.  At a quick glance, PR 73 looks like it provides more functionality, because it supports patterns, not just extensions, and it supports excluding directories as well as individual files. Would it cover your needs? Any reason you wouldn't prefer it?

**Comment by cpanato** [comment]
I'm not against it, just open it because I saw that PR after :/

I did some tests and that covers the use case we are looking to implement.

So I'm ok in close this in favor of #73 @mco-gh

**Comment by mco-gh** [comment]
Actually, on second thought, this covers the most common use case (extension based files) and it's a lot less involved (one file changed vs. 31) so I'm gonna go with this one. Thanks for the contrib! I may take the other one later but this feels like the safer option to add this functionality.

**Review by mco-gh — APPROVED** [review]

**Comment by Shabirmean** [comment]
@mco-gh - the 31 file changes on PR #73 is because I added extensive test cases :) Technically it only has one file change and everything else is a new test file added to validate different folder structures.

**Pull request merged**
