### PR TITLE
Add hcl extension

### PR DESCRIPTION
**Pull request by crazy-max**
Signed-off-by: CrazyMax <google@crazymax.dev>

### CODE REVIEW

**Comment by crazy-max** [comment]
@googlebot I signed it!

**Comment by willnorris** [comment]
Same as in #88, could you rebase this, and then [add `f.hcl` here](https://github.com/google/addlicense/blob/058aeeb7be096c4bcde8a2c0ceca2f6584fb5711/main_test.go#L312-L314).  No need for the testdata files.

**Comment by crazy-max** [comment]
@willnorris 

> could you rebase this, and then [add `f.hcl` here](https://github.com/google/addlicense/blob/058aeeb7be096c4bcde8a2c0ceca2f6584fb5711/main_test.go#L312-L314). No need for the testdata files.

Done.

**Comment by crazy-max** [comment]
@willnorris Oh and do I delete test files or I keep them for now?

**Comment by willnorris** [comment]
> @willnorris Oh and do I delete test files or I keep them for now?

either is fine.  They'll get removed when all the others do.

**Review by willnorris — APPROVED** [review]

**Pull request merged**
