### PR TITLE
Add support for Puppet manifests

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by willnorris** [comment]
would you mind also adding this to the relevant test case? https://github.com/google/addlicense/blob/9cc7ec3e36ab449bec29c9aea709c1969b97ace1/main_test.go#L319

**Comment by binford2k** [comment]
@willnorris apologies, I missed this before

**Comment by binford2k** [comment]
Ping @willnorris anything else I should do to get this merged?

**Review by willnorris — APPROVED** [review]

**Comment by willnorris** [comment]
could you try rebasing onto master?

**Comment by binford2k** [comment]
@willnorris done, thanks

**Pull request merged**
